[project]
name = "programinginpython"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.14"
dependencies = [
    "django==6.0.1",
    "djangorestframework==3.16.1",
    "scikit-learn==1.8.0",
]
